#!/bin/bash
SPAM=("http://" "ppa.launchpad.net/" "/ubuntu" ".com" "/deb")
ALL=(disco cosmic bionic artful zesty yakkety
	xenial wily vivid utopic trusty
	saucy raring quantal precise
	oneiric natty maverick lucid
	karmic jaunty intrepid hardy
	gutsy feisty edgy dapper
	breezy hoary warty)
RELEASES=()
#RELEASES=(wily vivid utopic trusty)
# Remember that arrays start at 0. So "seq 0 3" is 4
# releases starting with the leftmost one in the array.
for i in `seq 0 3`; do RELEASES+=("${ALL[$i]}"); done

if [ -t 1 ]; then
	ncolors=$(tput colors)
	if test -n "$ncolors" && test $ncolors -ge 8; then
		bold="$(tput bold)"
		normal="$(tput sgr0)"
		red="$(tput setaf 1)"
		green="$(tput setaf 2)"
		white="$(tput setaf 7)"
	fi
fi

sourcesFiles=$(ls /etc/apt/sources.list.d/ | grep -v .save)
repositoryList=$(cd /etc/apt/sources.list.d && cat $sourcesFiles /etc/apt/sources.list | grep deb\ http.* | sed -e 's/.*help\.ubuntu\.com.*//' -e 's/^#.*//' -e 's/deb\ //' -e 's/deb-src\ //' -e '/^$/d' | sort -u | awk '{print $1"|"$2}' | sed -e 's/\/|/|/' -e 's/-[a-z]*$//' | uniq && cd)

for index in ${!RELEASES[@]}; do
	printf "${white}${bold}${RELEASES[$index]^^}\t"
done
printf "REPOSITORY${normal}\n"

for repository in $repositoryList; do
	setDistro="$(echo $repository | sed 's/.*|//')"
	repoURL="$(echo $repository | sed 's/|.*//')"

	availableDistros=$(curl --silent $repoURL/dists/ | grep -oi href\=\"[^\/].*/\" | sed -e 's/href\=\"//i' -e 's/\/\"//' -e 's/-.*//' -e 's/\ NAME.*//i' | sort -u | uniq)
	if [ "$availableDistros" = "" ]; then
		availableDistros=$(curl --silent $repoURL/ | grep -oi href\=\"[^\/].*\" | sed -e 's/href\=\"//i' -e 's/\/\"//' -e 's/-.*//' -e 's/\ NAME.*//i' -e 's/\/index\.html\"//' -e 's/.*".*//' -e 's/http.*//' | sort -u | uniq)
	fi

	foundCurrent=false
	hadNo=false
	for index in ${!RELEASES[@]}; do
		if [[ $(echo "$availableDistros" | grep -oi "${RELEASES[$index]}") ]]; then
			if [ "$setDistro" = "${RELEASES[$index]}" ]; then
				foundCurrent=true
				if [ $index == 0 -o "$hadNo" = true ]; then
					printf "${green}[Yes]${normal}\t"
				else
					printf "[Yes]\t"
				fi
			else
				if ! $foundCurrent; then
					printf "${red}${bold}Yes${normal}\t"
				else
					printf "Yes\t"
				fi
			fi
		elif [ "$availableDistros" = "" ]; then
			printf "?\t" # For example the google chrome repo gives us a 404
		else
			hadNo=true
			printf "No\t"
		fi
	done
	for s in "${SPAM[@]}"; do
		repoURL=${repoURL#$s}
		repoURL=${repoURL%$s}
	done
	if [ "$foundCurrent" = true ]; then
		printf "$repoURL\n"
	else
		printf "$repoURL (${white}$setDistro${normal})\n"
	fi
done
printf "Thanks for all the fish.\n"
